### ISSUE TITLE
metadata issue 

### ISSUE THREAD

**Issue by romainGuiet** [BIOP/ijp-operetta-importer#10]
Hi folks  !

currently time steps is "false" and origin is 0,0
![image](https://user-images.githubusercontent.com/8309560/154018254-e3db270d-c124-470e-81ae-35a19c209028.png)

It would be nice if : 
- time step is correct 😉 
-it could be set with the actual position in the well 🎉 

Cheers,

R

**Comment by lacan** [comment]
last commit https://github.com/BIOP/ijp-operetta-importer/commit/3f918d41870a0c673df37037439250227e6d77d3 sets the xOrigin and yOrigin to the right micron based absolute stage coordinates.
Frame interval is also read and added
NOTE: The frame interval will be the original interval and will not be true if the user selects non-continuous timepoints during import. 
![image](https://user-images.githubusercontent.com/319932/154269326-b519ee20-a8d2-4105-89b7-aa6a502cae3f.png)

**Comment by NicoKiaru** [comment]
`sets the xOrigin and yOrigin to the right micron based absolute stage coordinates.`

I thought it was supposed to be pixels. Does it matter or not ?

**Comment by lacan** [comment]
It is whatever you want. Pixels are absolute and hard to locate. Physical real coordinates make more sense I think. You can get pixels by dividing with the calibration.
