### ISSUE TITLE
Github pages returns 404

### ISSUE THREAD

**Issue by NicoKiaru** [BIOP/ijp-operetta-importer#12]
The link on the readme returns 404 

Github pages is deployed however. No idea what's wrong

https://biop.github.io/ijp-operetta-importer/

**Comment by diligentgiantsquid** [comment]
Did you find a fix for this? I still get a 404 here-
Thanks

**Comment by NicoKiaru** [comment]
@lacan and maybe @Rdornier , the javadoc expert ;-), could you have a look at what's wrong here ? I'll try restarting a github action, if there's one available

**Comment by lacan** [comment]
The link was off, perhaps a change in the MVN handling. It's been updated. Ignore that it says JavaDoc for a snapshot version. It will be fixed on the next release
