### ISSUE TITLE
Error not finding top left coordinate

### ISSUE THREAD

**Issue by drooler89** [BIOP/ijp-operetta-importer#26]
Hi all, I have been trying to use this plugin to stitch my images obtained from the Opera Phenix HCS but I keep getting the error of not being able to find the top left coordinate. Any help would be greatly appreciated! 

[Log]
Well at R2-C2 is Well:0:0
Well at R2-C3 is Well:0:1
Well at R2-C4 is Well:0:2
Well at R2-C5 is Well:0:3
Well at R2-C6 is Well:0:4
Well at R2-C7 is Well:0:5
Well at R2-C8 is Well:0:6
Well at R2-C9 is Well:0:7
Well at R3-C2 is Well:0:8
Well at R3-C3 is Well:0:9
Well at R3-C4 is Well:0:10
Well at R3-C5 is Well:0:11
Well at R3-C6 is Well:0:12
Well at R3-C7 is Well:0:13
Well at R3-C8 is Well:0:14
Well at R3-C9 is Well:0:15
Well at R5-C2 is Well:0:16
Well at R5-C3 is Well:0:17
Well at R5-C4 is Well:0:18
Well at R5-C5 is Well:0:19
Well at R5-C6 is Well:0:20
Well at R5-C7 is Well:0:21
Well at R5-C8 is Well:0:22
Well at R5-C9 is Well:0:23
Well at R6-C2 is Well:0:24
Well at R6-C3 is Well:0:25
Well at R6-C4 is Well:0:26
Well at R6-C5 is Well:0:27
Well at R6-C6 is Well:0:28
Well at R6-C7 is Well:0:29
Well at R6-C8 is Well:0:30
Well at R6-C9 is Well:0:31
Well at R7-C2 is Well:0:32
Well at R7-C3 is Well:0:33
Well at R7-C4 is Well:0:34
Well at R7-C5 is Well:0:35
Well at R7-C6 is Well:0:36
Well at R7-C7 is Well:0:37
Well at R7-C8 is Well:0:38
Well at R7-C9 is Well:0:39
Well at R2-C2 is Well:0:0
Well at R2-C2 is Well:0:0
Well at R2-C2 is Well:0:0
Well: ome.xml.model.Well@1bee436c
Could not find top left coordinates for fields
Could not find top left coordinates for fields
[ERROR] Could not find coordinates for well ome.xml.model.Well@1bee436c

**Comment by lacan** [comment]
Dear @drooler89, 

Could you share the XML file you are tying to export? That way I can try to debug things on our side

**Comment by drooler89** [comment]
[Index.idx.xml.zip](https://github.com/BIOP/ijp-operetta-importer/files/11250143/Index.idx.xml.zip)

Here you go!

**Comment by lacan** [comment]
Awesome thank you. I think  I found the bug, and uploaded a new version. Please update from our update site and let me know if it works again.

**Comment by drooler89** [comment]
Hey thanks for the quick reply! Just tested it again and it works now. Thanks again!

**Comment by drooler89** [comment]
@lacan Hi, upon closer inspection of the stitched images, it seems that the order of stitching between different rows has been inverted. For example, images are currently stitched in the order of row 1,2,3,4 (from top to bottom), but should be row 4,3,2,1 (top top bottom). 

Heres an example of the stitched image (5x4) if that helps!

![C1-5x4 image](https://user-images.githubusercontent.com/130990012/232643049-0c0af780-f911-4684-b459-dfb9e574b02b.jpg)

**Comment by NicoKiaru** [comment]
@drooler89 don't you need to flip the images ?

We've added the flip options for Phenix compatibility (https://forum.image.sc/t/flip-images-option-for-biop-operetta-importer-plugin/78962)

**Comment by drooler89** [comment]
@NicoKiaru I have tried all three flip options but the stitching still seems wrong. I think the vertical option doesnt work. Heres pic of the stitched image after vertical flip which looks exactly the same as the one above (no flip used).

![C1-Vert](https://user-images.githubusercontent.com/130990012/232733247-d3bf38b4-139d-46e2-a8cc-d50ec7030958.jpg)

**Comment by lacan** [comment]
Moral of the story, never release on a Monday... Please try again and let me know.

All the best

Oli

**Comment by drooler89** [comment]
Works like a charm now! Thanks a bunch!
