### ISSUE TITLE
can not install in FIJI

### ISSUE THREAD

**Issue by shihanyu** [BIOP/ijp-operetta-importer#31]
After clicking Manage Update Sites

 Operetta Importer is not in the site list,

is it some mistake in my FIJI? 

could you please provide the site url, so that I can add it mannually

**Comment by NicoKiaru** [comment]
Oups, where did you see a mention of the 'Operetta Importer' update site ? That was a long time ago - this update site does not exists anymore. Just activate the PTBIOP update site and that will work.

Please re-open if that does not solve your issue.

Best, 

Nicolas
