### ISSUE TITLE
Error when wells exist (somehow) but no fields are found?

### ISSUE THREAD

**Issue by lacan** [BIOP/ijp-operetta-importer#6]
This error appeared when trying to export a well that apprently is found in the metadata but has no series...
Oddly enough, with the groovy version of the operetta importer, the field is not found..?
![image](https://user-images.githubusercontent.com/319932/126485729-d519770a-d6cd-4942-84c0-4ff0cfb6e9fc.png)

Also ofddly enough, the Operetta Harmony itself does not see the wells....

**Comment by NicoKiaru** [comment]
I think it's the same issue as https://github.com/BIOP/ijp-operetta-importer/issues/14. Should be fixed now
